// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: agents.proto

package agents_pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type AgentMessage_Type int32

const (
	AgentMessage_NULL         AgentMessage_Type = 0
	AgentMessage_ADD_AS_TAB   AgentMessage_Type = 1
	AgentMessage_GET_AS_TAB   AgentMessage_Type = 2
	AgentMessage_COUNT_AS_TAB AgentMessage_Type = 3
	AgentMessage_BRIDGE       AgentMessage_Type = 4
)

var AgentMessage_Type_name = map[int32]string{
	0: "NULL",
	1: "ADD_AS_TAB",
	2: "GET_AS_TAB",
	3: "COUNT_AS_TAB",
	4: "BRIDGE",
}
var AgentMessage_Type_value = map[string]int32{
	"NULL":         0,
	"ADD_AS_TAB":   1,
	"GET_AS_TAB":   2,
	"COUNT_AS_TAB": 3,
	"BRIDGE":       4,
}

func (x AgentMessage_Type) String() string {
	return proto.EnumName(AgentMessage_Type_name, int32(x))
}
func (AgentMessage_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_agents_37c3ae88d269b865, []int{0, 0}
}

type AgentMessage struct {
	// defines what type of message it is.
	Type                 AgentMessage_Type           `protobuf:"varint,1,opt,name=type,proto3,enum=agents.pb.AgentMessage_Type" json:"type,omitempty"`
	AgentServer          *AgentMessage_AgentServer   `protobuf:"bytes,2,opt,name=agentServer" json:"agentServer,omitempty"`
	AgentServerList      []*AgentMessage_AgentServer `protobuf:"bytes,3,rep,name=agentServerList" json:"agentServerList,omitempty"`
	Count                int32                       `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *AgentMessage) Reset()         { *m = AgentMessage{} }
func (m *AgentMessage) String() string { return proto.CompactTextString(m) }
func (*AgentMessage) ProtoMessage()    {}
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agents_37c3ae88d269b865, []int{0}
}
func (m *AgentMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentMessage.Unmarshal(m, b)
}
func (m *AgentMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentMessage.Marshal(b, m, deterministic)
}
func (dst *AgentMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentMessage.Merge(dst, src)
}
func (m *AgentMessage) XXX_Size() int {
	return xxx_messageInfo_AgentMessage.Size(m)
}
func (m *AgentMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AgentMessage proto.InternalMessageInfo

func (m *AgentMessage) GetType() AgentMessage_Type {
	if m != nil {
		return m.Type
	}
	return AgentMessage_NULL
}

func (m *AgentMessage) GetAgentServer() *AgentMessage_AgentServer {
	if m != nil {
		return m.AgentServer
	}
	return nil
}

func (m *AgentMessage) GetAgentServerList() []*AgentMessage_AgentServer {
	if m != nil {
		return m.AgentServerList
	}
	return nil
}

func (m *AgentMessage) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type AgentMessage_AgentServer struct {
	// protocol id
	Pid                  []byte   `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Peers                [][]byte `protobuf:"bytes,2,rep,name=peers" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentMessage_AgentServer) Reset()         { *m = AgentMessage_AgentServer{} }
func (m *AgentMessage_AgentServer) String() string { return proto.CompactTextString(m) }
func (*AgentMessage_AgentServer) ProtoMessage()    {}
func (*AgentMessage_AgentServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_agents_37c3ae88d269b865, []int{0, 0}
}
func (m *AgentMessage_AgentServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentMessage_AgentServer.Unmarshal(m, b)
}
func (m *AgentMessage_AgentServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentMessage_AgentServer.Marshal(b, m, deterministic)
}
func (dst *AgentMessage_AgentServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentMessage_AgentServer.Merge(dst, src)
}
func (m *AgentMessage_AgentServer) XXX_Size() int {
	return xxx_messageInfo_AgentMessage_AgentServer.Size(m)
}
func (m *AgentMessage_AgentServer) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentMessage_AgentServer.DiscardUnknown(m)
}

var xxx_messageInfo_AgentMessage_AgentServer proto.InternalMessageInfo

func (m *AgentMessage_AgentServer) GetPid() []byte {
	if m != nil {
		return m.Pid
	}
	return nil
}

func (m *AgentMessage_AgentServer) GetPeers() [][]byte {
	if m != nil {
		return m.Peers
	}
	return nil
}

func init() {
	proto.RegisterType((*AgentMessage)(nil), "agents.pb.AgentMessage")
	proto.RegisterType((*AgentMessage_AgentServer)(nil), "agents.pb.AgentMessage.AgentServer")
	proto.RegisterEnum("agents.pb.AgentMessage_Type", AgentMessage_Type_name, AgentMessage_Type_value)
}

func init() { proto.RegisterFile("agents.proto", fileDescriptor_agents_37c3ae88d269b865) }

var fileDescriptor_agents_37c3ae88d269b865 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x4a, 0xc3, 0x30,
	0x1c, 0x87, 0x6d, 0x93, 0x0d, 0xfd, 0x37, 0xcc, 0xf0, 0xc7, 0x43, 0x10, 0x0f, 0x61, 0x5e, 0x7a,
	0x2a, 0x32, 0xf1, 0x01, 0x32, 0x5b, 0x86, 0xd0, 0x55, 0xc8, 0xba, 0xf3, 0xd8, 0x34, 0x8c, 0x5d,
	0xd6, 0xd0, 0x44, 0x61, 0xcf, 0xed, 0x0b, 0x48, 0x3a, 0x36, 0x8b, 0x20, 0x78, 0xcb, 0x17, 0xbe,
	0x2f, 0xf0, 0x23, 0xc0, 0xd6, 0x5b, 0xb3, 0xf7, 0x2e, 0xb3, 0x6d, 0xe3, 0x1b, 0xbc, 0x3a, 0xd1,
	0x66, 0xfc, 0x15, 0x03, 0x53, 0x81, 0xe6, 0xc6, 0xb9, 0xf5, 0xd6, 0xe0, 0x03, 0x50, 0x7f, 0xb0,
	0x46, 0x44, 0x32, 0x4a, 0x47, 0x93, 0xbb, 0xec, 0xac, 0x66, 0x7d, 0x2d, 0xab, 0x0f, 0xd6, 0xe8,
	0xce, 0xc4, 0x02, 0x92, 0x4e, 0x5a, 0x98, 0xf6, 0xd3, 0xb4, 0x22, 0x96, 0x51, 0x9a, 0x4c, 0xee,
	0xff, 0x0a, 0xd5, 0x8f, 0xaa, 0xfb, 0x1d, 0xce, 0xe1, 0xba, 0x87, 0xe5, 0xce, 0x79, 0x41, 0x24,
	0xf9, 0xef, 0x53, 0xbf, 0x5b, 0xbc, 0x81, 0xc1, 0x5b, 0xf3, 0xb1, 0xf7, 0x82, 0xca, 0x28, 0x1d,
	0xe8, 0x23, 0xdc, 0x3e, 0x41, 0xd2, 0xab, 0x90, 0x03, 0xb1, 0xbb, 0xf7, 0x6e, 0x2b, 0xd3, 0xe1,
	0x18, 0x32, 0x6b, 0x4c, 0xeb, 0x44, 0x2c, 0x49, 0xca, 0xf4, 0x11, 0xc6, 0x15, 0xd0, 0x30, 0x18,
	0x2f, 0x81, 0x56, 0xcb, 0xb2, 0xe4, 0x17, 0x38, 0x02, 0x50, 0x79, 0xbe, 0x52, 0x8b, 0x55, 0xad,
	0xa6, 0x3c, 0x0a, 0x3c, 0x2b, 0xea, 0x13, 0xc7, 0xc8, 0x81, 0x3d, 0xbf, 0x2e, 0xab, 0xf3, 0x0d,
	0x41, 0x80, 0xe1, 0x54, 0xbf, 0xe4, 0xb3, 0x82, 0xd3, 0xcd, 0xb0, 0xfb, 0x87, 0xc7, 0xef, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xc8, 0xc0, 0x8f, 0x77, 0x97, 0x01, 0x00, 0x00,
}
