// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: agents.proto

package agents_pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type AgentMessage_Type int32

const (
	AgentMessage_NULL          AgentMessage_Type = 0
	AgentMessage_ADD_AS_TAB    AgentMessage_Type = 1
	AgentMessage_GET_AS_TAB    AgentMessage_Type = 2
	AgentMessage_COUNT_AS_TAB  AgentMessage_Type = 3
	AgentMessage_BRIDGE        AgentMessage_Type = 4
	AgentMessage_MY_LOCATION   AgentMessage_Type = 5
	AgentMessage_YOUR_LOCATION AgentMessage_Type = 6
)

var AgentMessage_Type_name = map[int32]string{
	0: "NULL",
	1: "ADD_AS_TAB",
	2: "GET_AS_TAB",
	3: "COUNT_AS_TAB",
	4: "BRIDGE",
	5: "MY_LOCATION",
	6: "YOUR_LOCATION",
}
var AgentMessage_Type_value = map[string]int32{
	"NULL":          0,
	"ADD_AS_TAB":    1,
	"GET_AS_TAB":    2,
	"COUNT_AS_TAB":  3,
	"BRIDGE":        4,
	"MY_LOCATION":   5,
	"YOUR_LOCATION": 6,
}

func (x AgentMessage_Type) String() string {
	return proto.EnumName(AgentMessage_Type_name, int32(x))
}
func (AgentMessage_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_agents_02f229e03769cd00, []int{0, 0}
}

type AgentMessage struct {
	// defines what type of message it is.
	Type                 AgentMessage_Type           `protobuf:"varint,1,opt,name=type,proto3,enum=agents.pb.AgentMessage_Type" json:"type,omitempty"`
	AgentServer          *AgentMessage_AgentServer   `protobuf:"bytes,2,opt,name=agentServer" json:"agentServer,omitempty"`
	AgentServerList      []*AgentMessage_AgentServer `protobuf:"bytes,3,rep,name=agentServerList" json:"agentServerList,omitempty"`
	Count                int32                       `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Location             *AgentMessage_Location      `protobuf:"bytes,5,opt,name=location" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *AgentMessage) Reset()         { *m = AgentMessage{} }
func (m *AgentMessage) String() string { return proto.CompactTextString(m) }
func (*AgentMessage) ProtoMessage()    {}
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agents_02f229e03769cd00, []int{0}
}
func (m *AgentMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentMessage.Unmarshal(m, b)
}
func (m *AgentMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentMessage.Marshal(b, m, deterministic)
}
func (dst *AgentMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentMessage.Merge(dst, src)
}
func (m *AgentMessage) XXX_Size() int {
	return xxx_messageInfo_AgentMessage.Size(m)
}
func (m *AgentMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AgentMessage proto.InternalMessageInfo

func (m *AgentMessage) GetType() AgentMessage_Type {
	if m != nil {
		return m.Type
	}
	return AgentMessage_NULL
}

func (m *AgentMessage) GetAgentServer() *AgentMessage_AgentServer {
	if m != nil {
		return m.AgentServer
	}
	return nil
}

func (m *AgentMessage) GetAgentServerList() []*AgentMessage_AgentServer {
	if m != nil {
		return m.AgentServerList
	}
	return nil
}

func (m *AgentMessage) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *AgentMessage) GetLocation() *AgentMessage_Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type AgentMessage_Location struct {
	Longitude            float32  `protobuf:"fixed32,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             float32  `protobuf:"fixed32,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Peer                 []byte   `protobuf:"bytes,3,opt,name=peer,proto3" json:"peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentMessage_Location) Reset()         { *m = AgentMessage_Location{} }
func (m *AgentMessage_Location) String() string { return proto.CompactTextString(m) }
func (*AgentMessage_Location) ProtoMessage()    {}
func (*AgentMessage_Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_agents_02f229e03769cd00, []int{0, 0}
}
func (m *AgentMessage_Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentMessage_Location.Unmarshal(m, b)
}
func (m *AgentMessage_Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentMessage_Location.Marshal(b, m, deterministic)
}
func (dst *AgentMessage_Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentMessage_Location.Merge(dst, src)
}
func (m *AgentMessage_Location) XXX_Size() int {
	return xxx_messageInfo_AgentMessage_Location.Size(m)
}
func (m *AgentMessage_Location) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentMessage_Location.DiscardUnknown(m)
}

var xxx_messageInfo_AgentMessage_Location proto.InternalMessageInfo

func (m *AgentMessage_Location) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *AgentMessage_Location) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *AgentMessage_Location) GetPeer() []byte {
	if m != nil {
		return m.Peer
	}
	return nil
}

type AgentMessage_AgentServer struct {
	// protocol id
	Pid []byte `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	// 兼容
	// 新的协议中每个 as 都带有坐标，所以这里要做兼容处理
	// repeated bytes peers = 2;
	// 新协议中的属性, 取代 peers 属性
	Locations            []*AgentMessage_Location `protobuf:"bytes,3,rep,name=locations" json:"locations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *AgentMessage_AgentServer) Reset()         { *m = AgentMessage_AgentServer{} }
func (m *AgentMessage_AgentServer) String() string { return proto.CompactTextString(m) }
func (*AgentMessage_AgentServer) ProtoMessage()    {}
func (*AgentMessage_AgentServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_agents_02f229e03769cd00, []int{0, 1}
}
func (m *AgentMessage_AgentServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentMessage_AgentServer.Unmarshal(m, b)
}
func (m *AgentMessage_AgentServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentMessage_AgentServer.Marshal(b, m, deterministic)
}
func (dst *AgentMessage_AgentServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentMessage_AgentServer.Merge(dst, src)
}
func (m *AgentMessage_AgentServer) XXX_Size() int {
	return xxx_messageInfo_AgentMessage_AgentServer.Size(m)
}
func (m *AgentMessage_AgentServer) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentMessage_AgentServer.DiscardUnknown(m)
}

var xxx_messageInfo_AgentMessage_AgentServer proto.InternalMessageInfo

func (m *AgentMessage_AgentServer) GetPid() []byte {
	if m != nil {
		return m.Pid
	}
	return nil
}

func (m *AgentMessage_AgentServer) GetLocations() []*AgentMessage_Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

func init() {
	proto.RegisterType((*AgentMessage)(nil), "agents.pb.AgentMessage")
	proto.RegisterType((*AgentMessage_Location)(nil), "agents.pb.AgentMessage.Location")
	proto.RegisterType((*AgentMessage_AgentServer)(nil), "agents.pb.AgentMessage.AgentServer")
	proto.RegisterEnum("agents.pb.AgentMessage_Type", AgentMessage_Type_name, AgentMessage_Type_value)
}

func init() { proto.RegisterFile("agents.proto", fileDescriptor_agents_02f229e03769cd00) }

var fileDescriptor_agents_02f229e03769cd00 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x8b, 0xb2, 0x50,
	0x14, 0xc6, 0x5f, 0xff, 0x85, 0x1d, 0x7d, 0xcb, 0xf7, 0xf0, 0x2e, 0x24, 0x5a, 0x48, 0xb3, 0x71,
	0x25, 0x43, 0xb3, 0x1d, 0x06, 0xec, 0x0f, 0x11, 0x58, 0xc2, 0xcd, 0x60, 0x5a, 0x89, 0xd5, 0x25,
	0x84, 0x50, 0xd1, 0xdb, 0x40, 0x1f, 0x75, 0xbe, 0xcd, 0xe0, 0xb5, 0x54, 0x06, 0x62, 0x66, 0x77,
	0x7f, 0xcf, 0x7d, 0x9e, 0x73, 0x8e, 0xc7, 0x0b, 0x7a, 0x74, 0xa2, 0x09, 0x2b, 0x9c, 0x2c, 0x4f,
	0x59, 0x8a, 0xdd, 0x3b, 0xed, 0x47, 0x9f, 0x32, 0xe8, 0x6e, 0x49, 0x2b, 0x5a, 0x14, 0xd1, 0x89,
	0xe2, 0x33, 0xc8, 0xec, 0x9a, 0x51, 0x53, 0xb0, 0x04, 0xbb, 0x37, 0x1e, 0x3a, 0xb5, 0xd5, 0x69,
	0xdb, 0x9c, 0xe0, 0x9a, 0x51, 0xc2, 0x9d, 0x38, 0x07, 0x8d, 0x9b, 0x36, 0x34, 0xff, 0xa0, 0xb9,
	0x29, 0x5a, 0x82, 0xad, 0x8d, 0x9f, 0x1e, 0x05, 0xdd, 0xc6, 0x4a, 0xda, 0x39, 0x5c, 0x41, 0xbf,
	0x85, 0x5e, 0x5c, 0x30, 0x53, 0xb2, 0xa4, 0xdf, 0x96, 0xfa, 0x9e, 0xc5, 0xff, 0xa0, 0x1c, 0xd2,
	0x4b, 0xc2, 0x4c, 0xd9, 0x12, 0x6c, 0x85, 0x54, 0x80, 0xaf, 0xa0, 0x9e, 0xd3, 0x43, 0xc4, 0xe2,
	0x34, 0x31, 0x15, 0x3e, 0xa8, 0xf5, 0xa8, 0xba, 0x77, 0xf3, 0x91, 0x3a, 0x31, 0x78, 0x07, 0xf5,
	0xae, 0xe2, 0x10, 0xba, 0xe7, 0x34, 0x39, 0xc5, 0xec, 0x72, 0xac, 0x96, 0x25, 0x92, 0x46, 0xc0,
	0x01, 0xa8, 0xe7, 0x88, 0x55, 0x97, 0x22, 0xbf, 0xac, 0x19, 0x11, 0xe4, 0x8c, 0xd2, 0xdc, 0x94,
	0x2c, 0xc1, 0xd6, 0x09, 0x3f, 0x0f, 0x42, 0xd0, 0x5a, 0x5f, 0x83, 0x06, 0x48, 0x59, 0x7c, 0xe4,
	0x65, 0x75, 0x52, 0x1e, 0xf1, 0xad, 0x6c, 0x57, 0xb5, 0x2e, 0x6e, 0x7b, 0xf9, 0x79, 0xf2, 0x26,
	0x32, 0xca, 0x41, 0x2e, 0x7f, 0x19, 0xaa, 0x20, 0xaf, 0xb7, 0x9e, 0x67, 0xfc, 0xc1, 0x1e, 0x80,
	0x3b, 0x9b, 0x85, 0xee, 0x26, 0x0c, 0xdc, 0x89, 0x21, 0x94, 0xbc, 0x98, 0x07, 0x77, 0x16, 0xd1,
	0x00, 0x7d, 0xea, 0x6f, 0xd7, 0xb5, 0x22, 0x21, 0x40, 0x67, 0x42, 0x96, 0xb3, 0xc5, 0xdc, 0x90,
	0xb1, 0x0f, 0xda, 0x6a, 0x17, 0x7a, 0xfe, 0xd4, 0x0d, 0x96, 0xfe, 0xda, 0x50, 0xf0, 0x1f, 0xfc,
	0xdd, 0xf9, 0x5b, 0xd2, 0x48, 0x9d, 0x7d, 0x87, 0xbf, 0xb6, 0x97, 0xaf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xc2, 0xf7, 0xda, 0xbe, 0x7d, 0x02, 0x00, 0x00,
}
